# Generated by Django 3.2.5 on 2021-08-01 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='email',
            field=models.EmailField(max_length=200, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Shop name'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='tel',
            field=models.CharField(max_length=30, verbose_name='Tel'),
        ),
    ]
